# Generated by Django 5.0.6 on 2024-06-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publishing_date',
            field=models.DateField(auto_now_add=True, verbose_name='Yayınlanma tarihi'),
        ),
    ]
