# Generated by Django 5.0.6 on 2024-07-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputName', models.CharField(max_length=100)),
                ('inputSurname', models.CharField(max_length=100)),
                ('inputAge', models.DateField()),
                ('inputGender', models.CharField(max_length=10)),
                ('inputPhoneNumber', models.CharField(max_length=20)),
                ('inputUniversity', models.CharField(blank=True, max_length=100, null=True)),
                ('inputCity', models.CharField(max_length=100)),
                ('inputkurum', models.CharField(blank=True, max_length=100, null=True)),
                ('inputUsername', models.EmailField(max_length=254)),
                ('inputPassword1', models.CharField(max_length=100)),
                ('inputPassword2', models.CharField(max_length=100)),
                ('interestAreas', models.TextField()),
                ('howFoundUs', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
